### ISSUE TITLE
Crash when rendering large document

### ISSUE THREAD

**Issue by drbarto** [marcbachmann/node-html-pdf#150]
When convering a rather large HTML document (containing about 40 images, each with about ~500kB), HTML-PDF crashes on my server (Ubuntu). Interestingly, it does not crash on my dev machine (OSX). Can someone give me a hint why this might be? Could it be due to limited RAM..? Here's the log output of the crash:

    "stack":"SyntaxError: Unexpected end of input
        at Object.parse (native)
        at ChildProcess.<anonymous> (/parse/cloud/node_modules/html-pdf/lib/pdf.js:117:21)
        at emitTwo (events.js:100:13)
        at ChildProcess.emit (events.js:185:7)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)"}

**Comment by marcbachmann** [comment]
Maybe phantomjs responds with something in stdout that the main process can't handle.
Check out https://github.com/marcbachmann/node-html-pdf/pull/141/files

**Comment by drbarto** [comment]
Thanks for your help! That patch didn't work for me, because it uses Node 6 API (namely `Buffer.from()`) and I'm stuck with 5.8. So I tried to change the patch to use the 'old' form of creating a Buffer (`var buffStr = new Buffer(stdout[i]).toString();`).

With the patch applied I get another error:

    TypeError: path must be a string
        at TypeError (native)
        at Object.fs.readFile (fs.js:262:11)
        at execPdfToBuffer (/parse/cloud/node_modules/html-pdf/lib/pdf.js:47:8)
        at ChildProcess.<anonymous> (/parse/cloud/node_modules/html-pdf/lib/pdf.js:146:14)
        at emitTwo (events.js:100:13)
        at ChildProcess.emit (events.js:185:7)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

The line numbers might be incorrect due to some log statements I added in `pdf.js`; anyway, the crash happens in `execPdfToBuffer` when calling `fs.readFile(res.filename, ...)`. Here, `res.filename` is `undefined`.
