### ISSUE TITLE
Not work in Ubuntu 14.04

### ISSUE THREAD

**Issue by ealiaga** [marcbachmann/node-html-pdf#153]
**This works fine on localhost but not in production.**    

My Options:
```

    var options = {
                        "type": "pdf",
                        "phantomPath": './node_modules/phantomjs-prebuilt/bin/phantomjs',
                        "phantomArgs": ['--ignore-ssl-errors=true'],
                        "timeout": 50000,
                        'format': 'Letter',      
                        'orientation': 'portrait',                  
                        'border': {     
                            'right': "1.91cm",
                            'left': "1.91cm"
                        },
                        'header': {
                            'height': '28mm'
                        },
                        'footer': {
                            'height': '28mm'
                        }
                    };
```
**The result in production:**
```
   Error: internal/child_process.js:278

    at ChildProcess.<anonymous> (/opt/optimizasalud/node_modules/html-pdf/lib/pdf.js:111:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
    at Process.onexit (/opt/optimizasalud/node_modules/async-listener/glue.js:188:31)

```
Does anyone know why this error occurs?

**Comment by vposudevsky** [comment]
I have the same issue in Debian 8.4

**Comment by vposudevsky** [comment]
The fix: sudo apt-get install libfontconfig

**Details:**
Thanks to this answer: https://github.com/ariya/phantomjs/issues/10904
