### ISSUE TITLE
Error: PDF generation timeout

### ISSUE THREAD

**Issue by lazaro92** [marcbachmann/node-html-pdf#189]
Hi, I'm getting this error when I'm generating pdf:
`Error: html-pdf: PDF generation timeout. Phantom.js script did not`exit.`
I have seen other issues like this but I haven't seen any solution.

This error only appears on Linux system, in a 8Gb RAM system. On Windows 10 it works fine, but I need it to run on Linux system.

The full error is:
`Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.
    at ChildProcess.<anonymous> (/home/albert/Documents/Git/Doxa-Codorniu/node_modules/html-pdf/lib/pdf.js:123:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
`

**Comment by txssseal** [comment]
set the timeout in the options
