### ISSUE TITLE
Not Working on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by kevincollins7** [marcbachmann/node-html-pdf#209]
I'm getting the dreaded 'Phantom.js script did not exit' error when using node-html-pdf on Ubuntu 16.04.1 LTS. The code is working fine on my local Windows 10 machine. I've already tried 'sudo apt-get install libfontconfig' and am still getting the same error.

Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.
    at ChildProcess.<anonymous> (/home/*****/*****/node_modules/html-pdf/lib/pdf.js:121:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

Any help would be greatly appreciated. Our API is running on this Ubuntu server and we were hoping to use this package to create PDF responses from certain endpoints.

**Comment by kevincollins7** [comment]
Disregard this! Got it working. I was trying to use an image in my html from an external website. Must of been some permission issues causing a timeout after the attempts to grab the image. I removed the image tag completely and the file was created. Should have tried that first!
