### ISSUE TITLE
报了这样一个error，搞了半天没解决，帮忙看看，谢谢~

### ISSUE THREAD

**Issue by dadaa1** [marcbachmann/node-html-pdf#218]
Error: html-pdf: Evaluation - SecurityError: DOM Exception 18: An attempt was ma
de to break through the security policy of the user agent.
Stack:
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/blog/script/post.min.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/blog/script/post.min.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js
  at https://sf-static.b0.upaiyun.com/v-585c9ea1/3rd/assets.js

    at ChildProcess.<anonymous> (G:\我的文件\素材包\node胡折腾\pachong\node_modu
les\.2.1.0@html-pdf\lib\pdf.js:121:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by martin-magakian** [comment]
Do you fix the issu ?

**Comment by MirrorXu** [comment]
晕  中文命名 ....
