### ISSUE TITLE
Spawn ENOENT

### ISSUE THREAD

**Issue by millysfabrielle** [marcbachmann/node-html-pdf#233]
I'm having somre troubles to create PDF file.

```
let html = "<p> HELLO ! </p>";
let OPTIONS = {phantomPath: './node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs'};
pdf.create(html, OPTIONS).toFile('output.pdf', function (err, res) {
                if (err){
                    console.log( "MESSAGE => ", err.message);
                    console.log( "ERROR => ", err);
                } 
                console.log(res);
            });

{ Error: spawn ./node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
at exports._errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:359:16)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
code: 'ENOENT',
errno: 'ENOENT',
syscall: 'spawn ./node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
path: './node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs',
spawnargs: [ '/usr/src/app/node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js' ] }
```

Using command-line example worked well.

**Comment by yogieputra8** [comment]
+1 I'm facing the same issue here

**Comment by vjsrinath** [comment]
+1 Me too facing the same issue.
BTW, I am running my application in docker. Is there any special attention needed.

**Comment by justinneff** [comment]
+1 Same issue. Also using docker. The same code works fine on Windows.

**Comment by yogieputra8** [comment]
@vjsrinath @justinneff try my solution on this thread https://github.com/marcbachmann/node-html-pdf/issues/212#issuecomment-280120314

**Comment by sohel-ahmed-ansari** [comment]
@vjsrinath @justinneff 
I was facing the same issue in docker. Managed to solve it though. The cause was that i had a global version of phantomjs already installed on my machine. Docker doesnt have access to module installed globally.

Solution: 
1. Remove globally installed phantomjs (**npm uninstall -g phantomjs**) 
2. Make sure **/usr/bin/phantomjs** doesnt exist. If it does, delete it.
3. Install phantomjs locally in the directory which is mounted on docker

Hope that works for you.

**Comment by nastassia7** [comment]
I am getting the same error...

I have tried:
1. uninstalling phantomjs globally & installing locally
2. npm rebuild phantomjs-prebuilt
3. versions of phantomjs-prebuilt 2.1.13 & 2.1.14
4. installing tar & bzip2 globally

(Mac OS X, node 4.6.1, html-pdf 2.1.0, phantomjs-prebuilt 2.1.13)

**Comment by JoeChapman** [comment]
Use the following 

```
const phantomPath = require('witch')('phantomjs-prebuilt', 'phantomjs');

pdf.create(options.template, {
    phantomPath: `${phantomPath}`,
    ...
})
```

**Comment by vjsrinath** [comment]
@sohel-ahmed-ansari the issue was happening when i was using the official node image based on alphine linux.
Later I created my own image based on ubuntu, it worked.
I didn't have to install phantomjs globally.
Take a look at my [Dockerfile](https://github.com/appsflare/html2pdf/blob/master/Dockerfile) 

Thanks

**Comment by sohel-ahmed-ansari** [comment]
@vjsrinath Didn't get what you mean. I already had global phantomjs installed, which was causing this issue. Had to remove the global version and install locally to solve it

**Comment by vjsrinath** [comment]
@sohel-ahmed-ansari I think we arrived at an issue from two different places.
I was facing this issue in my docker container that was created from node alphine linux image.
When i switched the base image to ubuntu it worked for me.

**Comment by kitko112** [comment]
I have this problem when I use `8.7.0-alpin` in my docker file. I got my problem solved just using `8.7.0-wheezy` instead, no source code changes.

**Comment by TheAmenRa** [comment]
Got this in Docker on Windows with a lot of Node images:

`Error: spawn EINVAL
      at _errnoException (util.js:1021:11)
      at ChildProcess.spawn (internal/child_process.js:325:11)
      at Object.exports.spawn (child_process.js:494:9)
      at PDF.PdfExec [as exec] (app/node_modules/html-pdf/lib/pdf.js:87:28)
      at PDF.PdfToFile [as toFile] (app/node_modules/html-pdf/lib/pdf.js:83:8)
      at Object.generateSD04 (app/src/helpers/pdfGenerator.js:66:29)
      at Context.it (app/tests/helpers.pdfCreator.test.js:44:18)`

It works on MacOS.

Any help?

**Comment by pepethree** [comment]
facing the same issue. command line example has the same error. works great on my dev site. any new fixes?

**Comment by sun2rise** [comment]
Why is this close? what's the official solution?

**Comment by Fabryprog** [comment]
```8.7.0-wheezy``` is the solution!!!

**Comment by sun2rise** [comment]
ciao! @Fabryprog, tnx but i was facing the same problem as @pepethree i think, or, at least it wasn't working for me.
my solution is now to use `node:8.11.1`

**Comment by infinito84** [comment]
Hi after searching everywhere I found this workaround that works on docker nodejs based on alpine:

Before npm install or yarn install to put this code:
RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C /

**Comment by elvizcacho** [comment]
@cristin Can you elaborate further what are you trying to do? 
If you are using html-pdf lib you have to set the global phantomjs path on the option object as the example below:
```
const options = {
  format: 'Legal',
  orientation: 'portrait',
  phantomPath: '/usr/local/bin/phantomjs'
};
```

**Comment by sudeepdk** [comment]
This will work 100 % -- follow this it worked for me ... 

const options = {
  format: 'Legal',
  orientation: 'portrait',
  phantomPath: '/usr/local/bin/phantomjs'
};

https://www.vultr.com/docs/how-to-install-phantomjs-on-ubuntu-16-04

**Comment by sun2rise** [comment]
@sudeepdk It does not with alpine..

```bash
> Step 2/17 : RUN apk --update --no-cache add   freetype   fontconfig   build-essential   chrpath   libssl-dev   libxft-dev   libfreetype6-dev   libfreetype6   libfontconfig1-dev   libfontconfig1   wget
>  ---> Running in 3018631de6a1
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
> ERROR: unsatisfiable constraints:
>   build-essential (missing):
>     required by: world[build-essential]
>   libfontconfig1 (missing):
>     required by: world[libfontconfig1]
>   libfontconfig1-dev (missing):
>     required by: world[libfontconfig1-dev]
>   libfreetype6 (missing):
>     required by: world[libfreetype6]
>   libfreetype6-dev (missing):
>     required by: world[libfreetype6-dev]
>   libssl-dev (missing):
>     required by: world[libssl-dev]
> Removing intermediate container 3018631de6a1
```

**Comment by LiangkunYu** [comment]
I experienced this situation with the wrong path of 
```  "runtimeExecutable": "/usr/local/bin/phantomjs",
```
after I correct it, the situation gone.

Macbook

**Comment by lipsakandhei** [comment]
I was having the exact issue in windows. I solved the problem by :
1. downloading, installing and extracting phantomjs for windows  phantomjs-2.1.1-windows.zip  from 
[https://phantomjs.org/download.html](url).
2. giving the path to the phantomjs.exe in my options variable:
`var options = { format: 'A4', "phantomPath": "C:\\Users\\HP\\Downloads\\phantomjs-2.1.1-windows\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe" , type: 'pdf',timeout: 30000};`

**Comment by vijaykondamudi** [comment]
@Guys - Any help is appreciated. I am seeing this error which downloading PDF 
{"err":{"errno":"ENOENT","code":"ENOENT","syscall":"spawn /usr/src/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs","path":"/usr/src/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs","spawnargs":["--ignore-ssl-errors=yes","/usr/src/app/node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js"]}}

**Comment by jerryOkafor** [comment]
> After trying @infinito84 solution and adding some extra dependencies I managed to make it work like this on this image **node:8.11.3-alpine**:
> 
> ```
> # Add support for https on wget
> RUN apk update && apk add --no-cache wget && apk --no-cache add openssl wget && apk add ca-certificates && update-ca-certificates
> 
> # Add phantomjs
> RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / \
>     && npm config set user 0 \
>     && npm install -g phantomjs-prebuilt
>     
> # Add fonts required by phantomjs to render html correctly
> RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family && rm -rf /var/cache/apk/*
> ```

This one worked for me.

**Comment by himanshu-alphonso** [comment]
> @jerryOkafor @elvizcacho I no longer get the phantomPath error but a new font error
> `Fontconfig warning: line 5: unknown element "its:rules" Fontconfig warning: line 6: unknown element "its:translateRule"`
> Any help appreciated

Facing the same issue.

**Comment by aniruddhasm** [comment]
@lipsakandhei I tried what you said but I am getting this error. 
**Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.**

```javascript
const options = {
  format: 'A4',
  phantomPath: ' C:\\Downloads\\ProjectName\\node_modules\\phantomjs-prebuilt\\lib\\phantom\\bin\\phantomjs.exe',
  renderDelay: 'manual'
}
```

Any assistance is greatly appreciated.

**Comment by andhareP** [comment]
I am facing same issue. Getting -{"errno":"ENOENT","code":"ENOENT","syscall":"spawn /app/node_modules/phantomjs-prebuilt/lib/phantom\\bin\\phantomjs.exe","path":"/app/node_modules/phantomjs-prebuilt/lib/phantom\\bin\\phantomjs.exe","spawnargs":["/app/node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js"]

I tried providing phantom path in options too but didn't help in resolving this issue.

Any help is highly appreciated.

**Comment by andhareP** [comment]
> @guys - Any help is appreciated. I am seeing this error which downloading PDF
> {"err":{"errno":"ENOENT","code":"ENOENT","syscall":"spawn /usr/src/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs","path":"/usr/src/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs","spawnargs":["--ignore-ssl-errors=yes","/usr/src/app/node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js"]}}

Were you abe to resolve this issue?

**Comment by andhareP** [comment]
> +1 Me too facing the same issue.
> BTW, I am running my application in docker. Is there any special attention needed.

I am facing same issue while running in docker, how did you fix issue in your case?

**Comment by dog1133299** [comment]
> After trying @infinito84 solution and adding some extra dependencies I managed to make it work like this on this image **node:8.11.3-alpine**:
> 
> ```
> # Add support for https on wget
> RUN apk update && apk add --no-cache wget && apk --no-cache add openssl wget && apk add ca-certificates && update-ca-certificates
> 
> # Add phantomjs
> RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / \
>     && npm config set user 0 \
>     && npm install -g phantomjs-prebuilt
>     
> # Add fonts required by phantomjs to render html correctly
> RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family && rm -rf /var/cache/apk/*
> ```

docker in node:alpin
I change 
>     && npm install -g phantomjs-prebuilt
to
```
    && npm uninstall -g phantomjs \
    && npm install phantomjs
```
that worked for me. thanks!

**Comment by selvarajprabhu** [comment]
> Hi after searching everywhere I found this workaround that works on docker nodejs based on alpine:
> 
> Before npm install or yarn install to put this code:
> RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C /

worked fantastic

**Comment by mcworox** [comment]
> Hi after searching everywhere I found this workaround that works on docker nodejs based on alpine:
> 
> Before npm install or yarn install to put this code:
> RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C /

If you have the same problem with node alphine images, THIS IS THE SOLUTION

**Comment by alihasnain1997** [comment]
> 1. npm uninstall -g phantomjs

didn't worked for me

**Comment by apurvns** [comment]
> Use the following
> 
> ```
> const phantomPath = require('witch')('phantomjs-prebuilt', 'phantomjs');
> 
> pdf.create(options.template, {
>     phantomPath: `${phantomPath}`,
>     ...
> })
> ```

I was struggling with this issue since 2 days, many solutions suggesting running phantomjs script inside docker container and uninstalling globally installed one didn't worked either , this one worked. Thanks

**Comment by alihasnain1997** [comment]
this is how it worked for me. Docker file:

FROM node:14-alpine
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .


# Add support for https on wget
RUN apk update && apk add --no-cache wget && apk --no-cache add openssl wget && apk add ca-certificates && update-ca-certificates

# Add phantomjs
RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / \
    && npm config set user 0 \
    && npm install -g phantomjs-prebuilt
    
# Add fonts required by phantomjs to render html correctly
RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation  && rm -rf /var/cache/apk/*
#RUN npm install
RUN npm install


# Copy app files
COPY . ./


# Expose port
EXPOSE $PORT

CMD [ "npm","start" ]

**Comment by du-camiloj** [comment]
> this is how it worked for me. Docker file:
> 
> FROM node:14-alpine
> 
> # Add a work directory
> WORKDIR /app
> 
> # Cache and Install dependencies
> COPY package.json .
> 
> # Add support for https on wget
> RUN apk update && apk add --no-cache wget && apk --no-cache add openssl wget && apk add ca-certificates && update-ca-certificates
> 
> # Add phantomjs
> RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / && npm config set user 0 && npm install -g phantomjs-prebuilt
> 
> # Add fonts required by phantomjs to render html correctly
> RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation && rm -rf /var/cache/apk/* #RUN npm install RUN npm install
> 
> # Copy app files
> COPY . ./
> 
> # Expose port
> EXPOSE $PORT
> 
> CMD [ "npm","start" ]

Did you add any path in the "phantomPath"?

**Comment by du-camiloj** [comment]
> this is how it worked for me. Docker file:
 
@alihasnain1997 Did you add any path in the phantomPath?

**Comment by alihasnain1997** [comment]
> > this is how it worked for me. Docker file:
> 
> @alihasnain1997 Did you add any path in the phantomPath?

@du-camiloj nope didn't added any path

**Comment by kasir-barati** [comment]
> Use the following
> 
> ```
> const phantomPath = require('witch')('phantomjs-prebuilt', 'phantomjs');
> 
> pdf.create(options.template, {
>     phantomPath: `${phantomPath}`,
>     ...
> })
> ```

Hello @JoeChapman
Why this way? In my case the `phantomjs-prebuilt` was in the `/path/to/project/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs` and the `file /path/to/project/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs` returned: 
```cmd
phantomjs: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.26, BuildID[sha1]=d0f2a21ff9e0b82113a2095e7cbca7dceaba88fb, stripped
```

Is there anything wrong with my file?

**Comment by kasir-barati** [comment]
> I have this problem when I use `8.7.0-alpin` in my docker file. I got my problem solved just using `8.7.0-wheezy` instead, no source code changes.

@kitko112 wheezy has no 16.x images or even 12.x. Did you change the base image again to other linux distros?

**Comment by kasir-barati** [comment]
> phantomPath
@mbarish-me Did you try this solution: https://github.com/marcbachmann/node-html-pdf/issues/233#issuecomment-289195523

**Comment by kasir-barati** [comment]
# From the future
I face it again. I am confused now

# This `Dockerfile` fixed my issue:

```Dockerfile
FROM node:16.14.0-alpine3.15

WORKDIR /app
COPY package*.json ./

# Add support for https on wget
RUN apk update && apk add --no-cache wget && apk --no-cache add openssl wget && apk add ca-certificates && update-ca-certificates

# Add phantomjs
RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / \
    && npm config set user 0 \
    && npm install -g phantomjs-prebuilt
    
# Add fonts required by phantomjs to render html correctly
RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation && rm -rf /var/cache/apk/*

# see this: https://github.com/marcbachmann/node-html-pdf/issues/563#issuecomment-712852134
RUN echo "" > /tmp/openssl.cnf

RUN npm install
# Rest of your Dockerfile, Instructions like COPY . /
```

# Side note:

If `npm install -g phantomjs-prebuilt` does not work, get rid of this line `&& npm config set user 0`

# README fore sure
And that's it, No need to pass `phantomPath` option to `create`. We finished. I hope this help you. **If your problem does not vanished, do not blame yourself. Computers are stupid enough. Nothing is wrong with you. Just try other solutions and give yourself 10 minute untrack. it will help you**

Best wishes.

**Comment by Dozalex** [comment]
Pain.
This Dockerfile fixed it for me. No need to pass `phantomPath` option.
```dockerfile
FROM node:12

WORKDIR /var/www

RUN apt-get update && apt-get install -y autoconf autogen libgl1-mesa-glx

# Rest of your Dockerfile, Instructions like COPY . /
```
With other node versions i got different errors.
Good luck.

**Comment by akmur** [comment]
@kasir-barati thanks for your solution, FYI I also had to add the following in my options for html-pdf

```
phantomPath: '/usr/local/bin/phantomjs',
```

**Comment by kevinmarangoni** [comment]
> 

> # From the future
> I face it again. I am confused now
> 
> # This `Dockerfile` fixed my issue:
> ```dockerfile
> FROM node:16.14.0-alpine3.15
> 
> WORKDIR /app
> COPY package*.json ./
> 
> # Add support for https on wget
> RUN apk update && apk add --no-cache wget && apk --no-cache add openssl wget && apk add ca-certificates && update-ca-certificates
> 
> # Add phantomjs
> RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / \
>     && npm config set user 0 \
>     && npm install -g phantomjs-prebuilt
>     
> # Add fonts required by phantomjs to render html correctly
> RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation && rm -rf /var/cache/apk/*
> 
> # see this: https://github.com/marcbachmann/node-html-pdf/issues/563#issuecomment-712852134
> RUN echo "" > /tmp/openssl.cnf
> 
> RUN npm install
> # Rest of your Dockerfile, Instructions like COPY . /
> ```
> 
> # Side note:
> If `npm install -g phantomjs-prebuilt` does not work, get rid of this line `&& npm config set user 0`
> 
> # README fore sure
> And that's it, No need to pass `phantomPath` option to `create`. We finished. I hope this help you. **If your problem does not vanished, do not blame yourself. Computers are stupid enough. Nothing is wrong with you. Just try other solutions and give yourself 10 minute untrack. it will help you**
> 
> Best wishes.

Give this man an Oscar

**Comment by aditya-786** [comment]
> > Use the following
> > ```
> > const phantomPath = require('witch')('phantomjs-prebuilt', 'phantomjs');
> > 
> > pdf.create(options.template, {
> >     phantomPath: `${phantomPath}`,
> >     ...
> > })
> > ```
> 
> I was struggling with this issue since 2 days, many solutions suggesting running phantomjs script inside docker container and uninstalling globally installed one didn't worked either , this one worked. Thanks

This worked for me. Thanks :)

**Comment by claudrocker** [comment]
> > 
> 
> > # From the future
> > I face it again. I am confused now
> > # This `Dockerfile` fixed my issue:
> > ```dockerfile
> > FROM node:16.14.0-alpine3.15
> > 
> > WORKDIR /app
> > COPY package*.json ./
> > 
> > # Add support for https on wget
> > RUN apk update && apk add --no-cache wget && apk --no-cache add openssl wget && apk add ca-certificates && update-ca-certificates
> > 
> > # Add phantomjs
> > RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / \
> >     && npm config set user 0 \
> >     && npm install -g phantomjs-prebuilt
> >     
> > # Add fonts required by phantomjs to render html correctly
> > RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation && rm -rf /var/cache/apk/*
> > 
> > # see this: https://github.com/marcbachmann/node-html-pdf/issues/563#issuecomment-712852134
> > RUN echo "" > /tmp/openssl.cnf
> > 
> > RUN npm install
> > # Rest of your Dockerfile, Instructions like COPY . /
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # Side note:
> > If `npm install -g phantomjs-prebuilt` does not work, get rid of this line `&& npm config set user 0`
> > # README fore sure
> > And that's it, No need to pass `phantomPath` option to `create`. We finished. I hope this help you. **If your problem does not vanished, do not blame yourself. Computers are stupid enough. Nothing is wrong with you. Just try other solutions and give yourself 10 minute untrack. it will help you**
> > Best wishes.
> 
> Give this man an Oscar

From an alternate future (2023) 
and using the container image: node:16.20-alpine
I had to add:

ENV OPENSSL_CONF=/etc/ssl/

before npm install.
 
Thank you guys! this a lifesaver post.

**Comment by DaniSanT17** [comment]
Thanks @claudrocker, your solution is the only that work for me, for while at least.

**Comment by mfalconi-perle** [comment]
@claudrocker 

running this script causes npm install to fail any ideas why? I even removed the script and now i cant even build anything and keep getting some error about puppeter

**Comment by claudrocker** [comment]
> @claudrocker
> 
> running this script causes npm install to fail any ideas why? I even removed the script and now i cant even build anything and keep getting some error about puppeter

I don't know but here is my Dockerfile, I hope it helps:

```
FROM node:16.20-alpine
WORKDIR /usr/src/app
COPY package*.json ./
# Add support for https on wget
RUN apk update && apk add --no-cache wget && apk --no-cache add openssl wget && apk add ca-certificates && update-ca-certificates
# Add phantomjs
RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / \
    && npm config set user 0 \
    && npm install -g phantomjs-prebuilt
# Add fonts required by phantomjs to render html correctly
RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation && rm -rf /var/cache/apk/*
# see this: https://github.com/marcbachmann/node-html-pdf/issues/563#issuecomment-712852134
RUN echo "" > /tmp/openssl.cnf
ENV OPENSSL_CONF=/etc/ssl/

RUN npm install
COPY . .
RUN npm run build

```

**Comment by arecaps** [comment]
https://github.com/dustinblackman/phantomized/ Has been archived. ☹️ 
What now?

**Comment by selvarajprabhu** [comment]
@arecaps Use this
https://github.com/fgrehm/docker-phantomjs2/releases/download/v2.0.0-20150722/dockerized-phantomjs.tar.gz

**Comment by Rifqio** [comment]
Here's my current dockerfile that works for me, hope this helps
```
FROM node:20.10.0-alpine
WORKDIR /app
COPY package*.json ./

# Add support for https on wget
RUN apk update && apk add --no-cache wget && apk --no-cache add openssl wget && apk add ca-certificates && update-ca-certificates

# Add phantomjs
RUN wget -qO- "https://github.com/fgrehm/docker-phantomjs2/releases/download/v2.0.0-20150722/dockerized-phantomjs.tar.gz" | tar xz -C / \
    && npm install -g phantomjs-prebuilt --force

# Add fonts required by phantomjs to render html correctly
RUN apk add --update ttf-dejavu ttf-droid ttf-freefont ttf-liberation && rm -rf /var/cache/apk/*

# see this: https://github.com/marcbachmann/node-html-pdf/issues/563#issuecomment-712852134
RUN echo "" > /tmp/openssl.cnf

# Rest of your docker command
```
