### ISSUE TITLE
Facing problem to generate PDF in Node

### ISSUE THREAD

**Issue by harshalyeole-tudip** [marcbachmann/node-html-pdf#242]
Hi,
We are generating PDF from the HTML template in Node.js.
Initially we are able to generate PDF using html-pdf library and also displayed API callback data in PDF. 
But after fetching images from server into PDF then it gives following error:
"Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.
at ChildProcess.<anonymous> (D:\projects\api\node_modules\html-pdf\lib\pdf.js:121:17)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)"

We also tried some alternative libraries to generate PDF but it gives same error as above.
Please help us to fix the problem.

**Comment by jeremypeter** [comment]
Had the same exact issue and it was due to an Amazon S3 outage. We were using absolute urls for our images stored in S3; which were inaccessible, making Phantomjs timeout.

**Comment by rafael-custodio** [comment]
I'm having this issue, how to fix it?

**Comment by andrienpecson** [comment]
+1
