### ISSUE TITLE
fontconfig error on Ubuntu 14.04.5

### ISSUE THREAD

**Issue by jasonburrows** [marcbachmann/node-html-pdf#246]
Hi - 

I have this working correctly on macOs 10.12.3, but when I deploy to Ubuntu 14.04.5 I get:

```
Error: Fontconfig error: 
     at ChildProcess.<anonymous> (/home/bitnami/svr/node_modules/html-pdf/lib/pdf.js:121:17)
     at emitTwo (events.js:106:13)
     at ChildProcess.emit (events.js:191:7)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12) +0ms
```

Version of fontconfig installed on Ubuntu is 2.11.0.
Node: 6.9.1
html-pdf: 2.1.0

Same HTML on either deployment.

I should note that until recently (like this month), it worked on macOS without fontconfig installed.  I had to install that recently to overcome a similar problem there.  I'm not sure what caused this difference but I suspect it was an update to macOS.  Regardless, it works there now.

**Comment by fabLouis** [comment]
I have the same issue on "Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux"

**Comment by Shefali25** [comment]
I was getting the same issue. I tried this.
Add the following to /etc/default/locale file

`LANG="en_US.UTF-8"`
`LANGUAGE="en_US.UTF-8"`
`LC_ALL="en_US.UTF-8"`

It worked.
