### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by uber1geek** [marcbachmann/node-html-pdf#276]
I am unable to figure out why this issue is occurring and the pdf file is also not being written to disk.

```
0|www      | ------------ INSIDE FN -------------
0|www      | -------- before pdf part ---------
0|www      | ------- INSIDE pdf creation -------
0|www      | filename:/var/www/html/public/pdfresults/readinesstest/1492667808.pdf
0|www      | GET /readinesspdf/createreadinesspdf/abcaxxxingh1x1@xyzmail.com/58ef022fa7c9152c47cb8dac 200 79.744 ms - 4581
0|www      | Error: read ECONNRESET
0|www      |     at exports._errnoException (util.js:1018:11)
0|www      |     at Pipe.onread (net.js:572:26)
PM2        | App [www] with id [0] and pid [13570], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:www id:0
PM2        | App name:www id:0 online
```

**Comment by uber1geek** [comment]
I fixed this issue by copying my global modules to my project folder. 
Apparently the node project was built on windows and i am deploying it to an ubuntu server. 
After installing the modules from package.json, they get installed to the global directory, I assume there is a mismatch due to OS conflict in the modules which was resolved by running this.

sudo cp -r /home/ubuntu/node_modules /var/www/html/
