### ISSUE TITLE
Error code ENOMEM in syscall spawn

### ISSUE THREAD

**Issue by phuthanhta** [marcbachmann/node-html-pdf#352]
Hi there,

I am facing the problem **ENOMEM** on production, it seems phantomjs is not be released, and server runs out of memory

It throws error (JSON format): {"code":"ENOMEM","errno":"ENOMEM","syscall":"spawn"}
Versions:
**html-pdf**: 2.2.0
**phantomjs-prebuilt**: 2.1.15

Environment: **Ubuntu 16.x**

Anyone gives me some advises, please

**Comment by rigbot01** [comment]
@phuthanhta : Any success in getting it working. I am also getting same issue.
```Error in HTML to PDF conversion :  { Error: spawn ENOMEM
at _errnoException (util.js:1031:13)
  at ChildProcess.spawn (internal/child_process.js:340:11)
  at Object.exports.spawn (child_process.js:499:9)
  at PDF.PdfExec [as exec] (/opt/src/node_modules/html-pdf/lib/pdf.js:87:28)
at PDF.PdfToFile [as toFile] (/opt/src/node_modules/html-pdf/lib/pdf.js:83:8)
 at Promise (/opt/src/build/server/server.bundle.js:18317:22)
 at new Promise (<anonymous>)
 at GeneratePortalHOSReport.<anonymous> (/opt/src/build/server/server.bundle.js:18314:29)
 at Generator.next (<anonymous>)
 at /opt/src/build/server/server.bundle.js:17569:71
   at new Promise (<anonymous>)
 at __awaiter (/opt/src/build/server/server.bundle.js:17565:12)
  at GeneratePortalHOSReport.convertHTMLAsPDF (/opt/src/build/server/server.bundle.js:18312:16)
  at GeneratePortalHOSReport.<anonymous> (/opt/src/build/server/server.bundle.js:17692:43)
 at Generator.next (<anonymous>)
  at fulfilled (/opt/src/build/server/server.bundle.js:17566:58)
  at <anonymous> errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }

**Comment by phuthanhta** [comment]
@rigbot01: just make sure you set timeout for the html-pdf process, secondly it launched one by one (synchronously)

**Comment by pengw00** [comment]
> @rigbot01: just make sure you set timeout for the html-pdf process, secondly it launched one by one (synchronously)

how to set timeout there?  can you explicit a little

**Comment by tathanhphu** [comment]
Set timeout value in the options parameter of create method.
More detail: https://github.com/marcbachmann/node-html-pdf/blob/master/lib/pdf.js (line #42)
