### ISSUE TITLE
Error: write EPIPE on bulk pdf generation

### ISSUE THREAD

**Issue by nkhlgpt** [marcbachmann/node-html-pdf#365]
Hi,
We are getting the following error 

```
Uncaught Error: write EPIPE
Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
```

Whenever we try to generate pdf in bulk like anything between 30 and 500 or 1000 

But when we are trying to generate a single pdf or even till 10 it works fine. So can anyone help regarding this?

**Comment by sreejithcj** [comment]
I am getting similar error intermittently. It will throw this error once when I try to create PDF for 5 or 6 times.

Unhandled rejection Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at Socket._writeGeneric (net.js:767:25)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)

**Comment by premaddx** [comment]
Try setting  { "phantomPath": "./node_modules/phantomjs/bin/phantomjs" } in the options. This worked for me

**Comment by sudeepdk** [comment]
This will work 100 % -- follow this it worked for me ... 

https://www.vultr.com/docs/how-to-install-phantomjs-on-ubuntu-16-04
