### ISSUE TITLE
cannot create pdf from html 

### ISSUE THREAD

**Issue by Nomercy10** [marcbachmann/node-html-pdf#366]
I am getting the following error:
html-pdf: Received the exit code '255'
Can't open '/scripts/pdf_a4_portrait.js'

    at ChildProcess.respond (/Users/rushikeshmhetre/rushi/mylambda/.webpack/service/emailSender.js:13617:71)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
Debug: internal, implementation, error 
    Error: Uncaught error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)
html-pdf: Received the exit code '255'Can't open '/scripts/pdf_a4_portrait.js'    at ChildProcess.respond (/Users/rushikeshmhetre/rushi/mylambda/.webpack/service/emailSender.js:13617:71)    at emitTwo (events.js:106:13)    at ChildProcess.emit (events.js:191:7)    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)Debug: internal, implementation, error     Error: Uncaught error: write EPIPE    at exports._errnoException (util.js:1026:11)    at WriteWrap.afterWrite (net.js:799:14)

**Comment by caffeinelogic** [comment]
I am getting the same error.
```
Error: html-pdf: Received the exit code '255'
Can't open '/scripts/pdf_a4_portrait.js'

    at ChildProcess.respond (/Users/XXXXXXX/workspace/project-name/generate-pdf.js:15365:31)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

That said, if I move the script into it's own directory (with it's own node_modules) I can call it from my app with no issues.

**Comment by Nomercy10** [comment]
Hi @caffeinelogic ,

I added a new key "script":(your_pdf_a4_potrait.js_path_here).

and it worked for me.

**Comment by marcbachmann** [comment]
I see you're using webpack to bundle your scripts.
How does your build pipeline look like? As long as you copy over the processing script to the new directory, it should still work.

**Comment by caffeinelogic** [comment]
@Nomercy10 
Thanks for the suggestion. I will take a shot at this in the next few days to see if that works.

@marcbachmann 
It works when its in its own directory, but fails when I couple it with the rest of the app. I am still reviewing how it is bundling. I might be getting some 'dependency leakage' from the other webpack config. I'll post back once I try some additional tweaks...
