### ISSUE TITLE
{ Error: write EPIPE

### ISSUE THREAD

**Issue by tapasgiri9** [marcbachmann/node-html-pdf#373]
{ Error: write EPIPE

    at _errnoException (util.js:1024:11)

    at Socket._writeGeneric (net.js:770:25)

    at Socket._write (net.js:789:8)

    at doWrite (_stream_writable.js:387:12)

    at writeOrBuffer (_stream_writable.js:373:5)

    at Socket.Writable.write (_stream_writable.js:290:11)

    at Socket.write (net.js:707:40)

While trying to generate the  pdf file this is the error I am getting. 
Any help will be appreciated.

**Comment by kernel72** [comment]
Looks like problem with phantomjs itself. 
When I had tried to execute installed by dependency version of phantomjs it throws error:

`error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`

After install lib fontconfig (on centos-7) problem resolved.

**Comment by 89466598946659** [comment]
@tapasgiri9  The same problem with me. Do you resolve it?

**Comment by premaddx** [comment]
Try setting { "phantomPath": "./node_modules/phantomjs/bin/phantomjs" } in the options. This worked for me.

**Comment by francois-legoff** [comment]
pdfOption.phantomPath = require('phantomjs').path worked for me
