### ISSUE TITLE
PhantomJS crashes with exit code 3221225477

### ISSUE THREAD

**Issue by 4D48** [marcbachmann/node-html-pdf#377]
Input is HTML with 250 big images.
`Error: html-pdf: Received the exit code '3221225477'
Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

    at ChildProcess.respond (C:\xampp\htdocs\SPRO\viewer\node_modules\html-pdf\lib\pdf.js:121:31)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)`

**Comment by bhavin00** [comment]
Any Fixes found on this ?

**Comment by antwaanh** [comment]
@bhavin00 have you found a solution yourself?

**Comment by bhavin00** [comment]
@antwaanh. ... yes i found solution.. actually it need more server ram when there is big size html .. so, I give my html pdf function to use flexible memory instead of 2gb.. So , It works fine for me

**Comment by bhavin00** [comment]
This is not the issue of this module.. so, I think makers can close

**Comment by antwaanh** [comment]
Thanks for your help @bhavin00

**Comment by AnthonyPhan** [comment]
I'm experiencing this same issue.
We are using node-html-pdf in our server less application (Azure function apps) which can only have a maximum of 1.5GB ram on a consumption based plan. Is there any way to reduce the amount of ram required?

**Comment by Hiti3** [comment]
Please explain the solution! So just bumping the server ram amount will resolve it..?

**Comment by Syn0** [comment]
Same error, simple html crashed the Azure function App.
Can someone explain plz ?
