### ISSUE TITLE
Received the exit code '255'

### ISSUE THREAD

**Issue by sun2rise** [marcbachmann/node-html-pdf#415]
Hi
I am using this script inside a folder of a create-react-app project because i need it there in order to use [Netlify function](https://www.netlify.com/docs/functions/) (like aws lambda).

I am using options like this because otherwise it won't find pdf_a4_portrait.js:

```js
const options = {
  script: './../../node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js',
  format: 'A4'
};
```

but still i have this error:

```
Error: html-pdf: Received the exit code '255'
Can't open '../../node_modules/html-pdf/lib/scripts/pdf_a4_portrait.js'

    at ChildProcess.respond (/Users/sunrising/Documents/Projects/testproject/lambda/htmlToPdfBlob.js:25177:31)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

Is there any solution?
I am trying to use this in a [Netlify function](https://www.netlify.com/docs/functions/) (like aws lambda).

#366 didn't help

**Comment by estebanmh95** [comment]
Hi. Did you solve this issue? Where did you add the options object? Thanks
