### ISSUE TITLE
Installing issue phantomjs dependency error

### ISSUE THREAD

**Issue by valdorvaldor** [marcbachmann/node-html-pdf#417]
Perhaps not related to this project but phantomjs-prebuilt, however I'm reporting this because my installation failed. 

npm --version 5.6

`
> phantomjs-prebuilt@2.1.16 install node_modules/phantomjs-prebuilt
> node install.js

module.js:549
    throw err;
    ^

Error: Cannot find module node_modules/phantomjs-prebuilt/install.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm WARN ms_pdf@1.0.0 No repository field.
npm WARN ms_pdf@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by ricklambrechts** [comment]
At first i had this problem, after removing node_modules folder and an npm install i dont have to install the phantomjs package. Maybe you could try that?
