### ISSUE TITLE
Error: html-pdf: PDF generation timeout. Phantom.js script did not exit

### ISSUE THREAD

**Issue by Robson-Ferreira** [marcbachmann/node-html-pdf#494]
I already change the timeout to a high number, but is doesn't work.
I am using a Debian system with 16GB RAM.

**Comment by davejlin** [comment]
My colleague encountered the same problem:

`Error returned from PDF generation Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.
at Timeout.execTimeout (/Users/qtb0808/Documents/Repos/Cards/jira-card-generator-master/node_modules/html-pdf/lib/pdf.js:91:19)
at listOnTimeout (internal/timers.js:535:17)
at processTimers (internal/timers.js:479:7) `

**Comment by nyel-dev** [comment]
Anyone got this figured out?

**Comment by vipulphysiofirst** [comment]
i also have the same problem ..Anyone got this figured out?

**Comment by aniruddhasm** [comment]
I am also facing the same issue... Anyone found something?

**Comment by Prasundas99** [comment]
+1

**Comment by jpgupta** [comment]
+1

**Comment by YahiaKhaled** [comment]
+1

**Comment by digonto0912** [comment]
+1
