### ISSUE TITLE
SIGKILL

### ISSUE THREAD

**Issue by mukeshsharma1426** [marcbachmann/node-html-pdf#528]
Getting SIGKILL in docker deployment while converting html to pdf. while it is working fine with ec2 instance.
Points to consider
1. It works perfectly fine sometimes and returns SIGKILL error few times.
2. Size of pdf is 44 MB.
3. working fine for small amount of data as well.

Issue is  SIGKILL undefined
Trace: 1111111  SIGKILL at /app/routes/pdf.js:55:17
    at execPdfToBuffer (/app/node_modules/html-pdf/lib/pdf.js:45:21) 
    at ChildProcess.respond (/app/node_modules/html-pdf/lib/pdf.js:126:14)  
    at emitTwo (events.js:106:13) 
    at ChildProcess.emit (events.js:191:7) 
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by manuks** [comment]
Did you get any clue?
Is it because we are running the application as a docker container?
Or anything related to phantomjs timeout?
Any idea to fix it?

**Comment by mukeshsharma1426** [comment]
In our case, it was basically Memory Issue only. On an urgent basis, we increased containers memory and later on shifted to puppeteer.
