### ISSUE TITLE
While creating PDF invoice: ERROR: WRITE PIPE

### ISSUE THREAD

**Issue by udit1109** [marcbachmann/node-html-pdf#585]
^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at PDF.PdfExec [as exec] (C:\Users\uditu\AppData\Roaming\npm\node_modules\html-pdf\lib\pdf.js:142:15)
    at PDF.PdfToFile [as toFile] (C:\Users\uditu\AppData\Roaming\npm\node_modules\html-pdf\lib\pdf.js:84:8)
    at C:\Users\uditu\xm-admin\modules\users\server\controllers\users\users.customisedInvoice.server.controller.js:100:35
    at Query.<anonymous> (C:\Users\uditu\xm-admin\node_modules\mongoose\lib\query.js:2139:28)
    at C:\Users\uditu\xm-admin\node_modules\kareem\index.js:177:19
    at C:\Users\uditu\xm-admin\node_modules\kareem\index.js:109:16
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4047,
  code: 'EPIPE',
  syscall: 'write'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by JuanM04** [comment]
Similar to #576
