### ISSUE TITLE
Issue with Html-Pdf for node js

### ISSUE THREAD

**Issue by jschaeppi** [marcbachmann/node-html-pdf#596]
I've recently encountered a bug that is causing an error when I use a font awesome icon in my html that is being used to convert to pdf.   I haven't been able to find anything when searching for this issue so not sure if this is new or not enough people have experienced this.  Below are the error codes:
html-pdf: Evaluation - Font Awesome Kit: Error
Stack: at https://kit.fontawesome.com/b46fe6b39d.js
at ChildProcess.respond (<path to node modules>frontend/node_modules/html-pdf/lib/pdf.js:121:31)
at ChildProcess.emit (events.js:315:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

I hope that a resolution can be found for this as I would like to use the icons I was using.

**Comment by davideavanzi** [comment]
Hello, i'm having the same issue. 
@jschaeppi  did you find any solution to this issue?

**Comment by DirectriX01** [comment]
How did you go about this error @davideavanzi ?
