### ISSUE TITLE
QR code not visible over generated pdf post ami upgrade

### ISSUE THREAD

**Issue by srrao11** [marcbachmann/node-html-pdf#692]
I have recently migrated my ec2 instance from ami1 to ami2. Post upgrade the qr code (which is usually a byte array) is not getting generated. 
Also during upgrade i was getting error like :
```
{
"stack": "Error: /opt/boson/userTravellerProfile/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory\n\n    
 at ChildProcess.<anonymous> (/opt/boson/userTravellerProfile/node_modules/html-pdf/lib/pdf.js:121:17)\n    
 at emitTwo (events.js:126:13)\n    at ChildProcess.emit (events.js:214:7)\n    
 at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)",
"message": "/opt/boson/userTravellerProfile/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory\n"
}
```
So i installed fontconfig : sudo yum install -y fontconfig

**Comment by srrao11** [comment]
The qr code is present as an html image tag `<img src='some-url'>` which fetches byte array from an url.

**Comment by srrao11** [comment]
Instead of passing `<img src='some-url'> `.   now i am passing base64 encoded string like `<img src="data:image/jpg;base64,<encoded-string>" >`
