### ISSUE TITLE
Failed to load PhantomJS module

### ISSUE THREAD

**Issue by jitendrapardhi7709** [marcbachmann/node-html-pdf#712]
Error in Payment Status: AssertionError [ERR_ASSERTION]: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'
0|cdc_middleware  |     at new PDF (/home/CDC_Middleware_Application/node_modules/html-pdf/lib/pdf.js:40:3)
0|cdc_middleware  |     at Object.createPdf [as create] (/home/CDC_Middleware_Application/node_modules/html-pdf/lib/index.js:10:14)
0|cdc_middleware  |     at Object.generateInvoicePDF (/home/CDC_Middleware_Application/utility/torrentBillDeskService.js:776:13)
0|cdc_middleware  |     at module.exports (/home/CDC_Middleware_Application/controllers/torrentPaymentStatus.js:26:38)
0|cdc_middleware  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
0|cdc_middleware  |   generatedMessage: false,
0|cdc_middleware  |   code: 'ERR_ASSERTION',
0|cdc_middleware  |   actual: undefined,
0|cdc_middleware  |   expected: true,
0|cdc_middleware  |   operator: '=='
0|cdc_middleware  | }
  I keep encountering this error on the CentOS server with an ARM64 processor and Node.js version 20. Can anyone suggest how to resolve this issue?

**Comment by Himanshu4833** [comment]
let options = {
            childProcessOptions: {
                env: {
                    OPENSSL_CONF: '/dev/null',
                },
            },
    }
    
    I think this work for you.

**Comment by jitendrapardhi7709** [comment]
> let options = { childProcessOptions: { env: { OPENSSL_CONF: '/dev/null', }, }, }
> 
> ```
> I think this work for you.
> ```

Thanks for your suggestion @Himanshu4833.
