### ISSUE TITLE
Issue using command line

### ISSUE THREAD

**Issue by anthonycluse** [marcbachmann/node-html-pdf#77]
Hello,

I get an issue using HTML-PDF on my remote server (RedHat Linux).

Command : 

    html-pdf index.html print.pdf

Result : 

    events.js:85
      throw er; // Unhandled 'error' event
            ^
    Error: write EPIPE
      at exports._errnoException (util.js:746:11)
      at WriteWrap.afterWrite (net.js:775:14)

**Comment by grsabreu** [comment]
@anthonycluse did you solve it?

**Comment by anthonycluse** [comment]
Yes that was an issue with dependencies... 

I've solved it by install "imagemagick" and "phantomjs".

**Comment by marcbachmann** [comment]
imagemagick isn't needed. Also phantomjs should get installed automatically.
